defmodule ExAthena.Compactors.Summary do
  @moduledoc """
  Default `ExAthena.Compactor` — replaces the middle of message history
  with a short LLM-generated summary.

  Strategy:

    1. Keep the pinned prefix intact (system prompt + any pinned rules).
    2. Keep the live suffix intact (most recent `:live_suffix_count`
       messages).
    3. Summarise everything between into one terse assistant-role message
       tagged `metadata: %{compacted: true}` so the model knows it's a
       digest of prior turns, not fresh context.

  The summary is generated by calling the same provider the loop is
  using. Cost counts against the run's budget.

  ## Config

      config :ex_athena, :compactor,
        pinned_prefix_count: 1,
        live_suffix_count: 6,
        summary_system_prompt: "…"
  """

  @behaviour ExAthena.Compactor
  @behaviour ExAthena.Compactor.Stage

  alias ExAthena.{Budget, Compactor, Messages, Request}
  alias ExAthena.Loop.State
  alias ExAthena.Messages.Message

  @default_pinned_prefix_count 1
  @default_live_suffix_count 6
  @default_compact_at 0.6

  @impl ExAthena.Compactor
  def should_compact?(%State{} = state, %{tokens: tokens, max_tokens: max}) do
    threshold = compact_at(state)
    max > 0 and tokens >= trunc(threshold * max)
  end

  @impl ExAthena.Compactor.Stage
  def name, do: :summary

  @impl ExAthena.Compactor
  def compact(%State{} = state, estimate) do
    pinned = effective_pinned_prefix_count(state)
    live = live_suffix_count(state)

    {prefix, middle, suffix} = split_messages(state.messages, pinned, live)

    cond do
      middle == [] ->
        :skip

      length(middle) < 3 ->
        # Not enough to bother summarising.
        :skip

      true ->
        do_compact(prefix, middle, suffix, state, estimate)
    end
  end

  # Pipeline-stage entry point. Adapts the legacy {:compact, msgs, meta}
  # tuple to the Stage `{:ok, state, estimate}` shape expected by
  # `Compactor.Pipeline`. The Compactor.compact/2 callback above is
  # what direct Compactor consumers (and pre-PR2 loop installs) call.
  @impl ExAthena.Compactor.Stage
  @spec compact_stage(State.t(), Compactor.estimate()) :: ExAthena.Compactor.Stage.result()
  def compact_stage(%State{} = state, estimate) do
    case compact(state, estimate) do
      {:compact, new_messages, metadata} ->
        new_state = %{
          state
          | messages: new_messages,
            budget: Map.get(metadata, :budget, state.budget)
        }

        {:ok, new_state, %{estimate | tokens: Map.get(metadata, :after, estimate.tokens)}}

      :skip ->
        :skip

      {:error, _} = err ->
        err
    end
  end

  # ── Internal ──────────────────────────────────────────────────────

  defp do_compact(prefix, middle, suffix, %State{} = state, estimate) do
    case summarise(middle, state) do
      {:ok, summary_text, summary_usage} ->
        summary_msg = %Message{
          role: :assistant,
          content: summary_text,
          name: "compactor_summary"
        }

        new_messages = prefix ++ [summary_msg] ++ suffix

        new_budget = Budget.add(state.budget || Budget.new(), summary_usage, nil)

        metadata = %{
          before: estimate.tokens,
          after: ExAthena.Compactor.estimate_tokens(new_messages),
          dropped_count: length(middle),
          reason: :token_budget,
          budget: new_budget
        }

        {:compact, new_messages, metadata}

      {:error, reason} ->
        {:error, {:summary_failed, reason}}
    end
  end

  defp summarise(middle, state) do
    instruction =
      summary_system_prompt() <>
        "\n\nSummarise the following conversation turns as a single paragraph " <>
        "focusing on decisions, tool results, and open questions. Be terse."

    req_messages = middle ++ [Messages.user(instruction)]

    request = %Request{
      messages: req_messages,
      system_prompt: nil,
      model: state.request_template && state.request_template.model,
      max_tokens: 512,
      temperature: 0.2,
      timeout_ms: 30_000
    }

    case state.provider_mod.query(request, state.provider_opts) do
      {:ok, %{text: text} = response} when is_binary(text) and text != "" ->
        {:ok, text, response.usage}

      {:ok, _} ->
        {:error, :empty_summary}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp split_messages(messages, pinned_count, live_count) do
    total = length(messages)

    cond do
      total <= pinned_count + live_count ->
        {messages, [], []}

      true ->
        {prefix, rest} = Enum.split(messages, pinned_count)
        {middle, suffix} = Enum.split(rest, max(0, length(rest) - live_count))
        {prefix, middle, suffix}
    end
  end

  # Effective pinned prefix = configured prefix slots + however many
  # memory-context messages and pre-loaded skill activation messages got
  # prepended at run start. Memory and pre-loaded skills (PR1) live at
  # the top of the message list, so we extend the pin floor to keep
  # them safe across compactions.
  defp effective_pinned_prefix_count(%State{meta: meta} = state) do
    pinned_prefix_count(state) +
      Map.get(meta, :memory_count, 0) +
      Map.get(meta, :preloaded_skill_count, 0)
  end

  defp pinned_prefix_count(%State{meta: meta}),
    do:
      Map.get(meta, :pinned_prefix_count) ||
        config(:pinned_prefix_count, @default_pinned_prefix_count)

  defp live_suffix_count(%State{meta: meta}),
    do:
      Map.get(meta, :live_suffix_count) || config(:live_suffix_count, @default_live_suffix_count)

  defp compact_at(%State{meta: meta}),
    do: Map.get(meta, :compact_at) || config(:compact_at, @default_compact_at)

  defp summary_system_prompt do
    config(
      :summary_system_prompt,
      "You are a compaction assistant. Your only job is to summarise a portion of a " <>
        "conversation between an engineer and an AI agent so the agent can continue " <>
        "without the full transcript."
    )
  end

  defp config(key, default) do
    case Application.get_env(:ex_athena, :compactor) do
      nil -> default
      kw when is_list(kw) -> Keyword.get(kw, key, default)
      map when is_map(map) -> Map.get(map, key, default)
    end
  end
end
