defmodule ExAthena.Compactors.Summary do
  @moduledoc """
  Default `ExAthena.Compactor` — replaces the middle of message history
  with a short LLM-generated summary.

  Strategy:

    1. Keep the pinned prefix intact (system prompt + any pinned rules).
    2. Keep the live suffix intact (most recent `:live_suffix_count`
       messages).
    3. Summarise everything between into one terse assistant-role message
       tagged `metadata: %{compacted: true}` so the model knows it's a
       digest of prior turns, not fresh context.

  The summary is generated by calling the same provider the loop is
  using. Cost counts against the run's budget.

  ## Config

      config :ex_athena, :compactor,
        pinned_prefix_count: 1,
        live_suffix_count: 6,
        summary_system_prompt: "…"
  """

  @behaviour ExAthena.Compactor
  @behaviour ExAthena.Compactor.Stage

  alias ExAthena.{Compactor, Messages, Request}
  alias ExAthena.Compactor.Config
  alias ExAthena.Loop.State
  alias ExAthena.Messages.Message

  @default_pinned_prefix_count 1
  @default_live_suffix_count 6
  @default_compact_at 0.6

  @impl ExAthena.Compactor
  def should_compact?(%State{} = state, %{tokens: tokens, max_tokens: max}) do
    threshold = compact_at(state)
    max > 0 and tokens >= trunc(threshold * max)
  end

  @impl ExAthena.Compactor.Stage
  def name, do: :summary

  @impl ExAthena.Compactor
  def compact(%State{} = state, estimate) do
    pinned = effective_pinned_prefix_count(state)
    live = live_suffix_count(state)

    {prefix, middle, suffix} = split_messages(state.messages, pinned, live)

    cond do
      middle == [] ->
        :skip

      length(middle) < 3 ->
        # Not enough to bother summarising.
        :skip

      true ->
        do_compact(prefix, middle, suffix, state, estimate)
    end
  end

  # Pipeline-stage entry point. Adapts the legacy {:compact, msgs, meta}
  # tuple to the Stage `{:ok, state, estimate}` shape expected by
  # `Compactor.Pipeline`. The Compactor.compact/2 callback above is
  # what direct Compactor consumers (and pre-PR2 loop installs) call.
  @impl ExAthena.Compactor.Stage
  @spec compact_stage(State.t(), Compactor.estimate()) :: ExAthena.Compactor.Stage.result()
  def compact_stage(%State{} = state, estimate) do
    case compact(state, estimate) do
      {:compact, new_messages, metadata} ->
        new_state = %{
          state
          | messages: new_messages,
            budget: Map.get(metadata, :budget, state.budget)
        }

        {:ok, new_state, %{estimate | tokens: Map.get(metadata, :after, estimate.tokens)}}

      :skip ->
        :skip

      {:error, _} = err ->
        err
    end
  end

  # ── Internal ──────────────────────────────────────────────────────

  defp do_compact(prefix, middle, suffix, %State{} = state, estimate) do
    {pinned_in_middle, summarisable} = Enum.split_with(middle, & &1.pin)

    case summarisable do
      [] ->
        :skip

      few when length(few) < 3 ->
        :skip

      _ ->
        case summarise(summarisable, state) do
          {:ok, summary_text, new_budget} ->
            summary_msg = %Message{
              role: :assistant,
              content: summary_text,
              name: "compactor_summary"
            }

            new_messages = prefix ++ [summary_msg] ++ pinned_in_middle ++ suffix

            metadata = %{
              before: estimate.tokens,
              after: Compactor.estimate_tokens(new_messages, Compactor.system_prompt(state)),
              dropped_count: length(summarisable),
              reason: :token_budget,
              budget: new_budget
            }

            {:compact, new_messages, metadata}

          {:error, reason} ->
            {:error, {:summary_failed, reason}}
        end
    end
  end

  defp summarise(middle, state) do
    instruction =
      summary_system_prompt() <>
        "\n\nSummarise the following conversation turns as a single paragraph " <>
        "focusing on decisions, tool results, and open questions. Be terse."

    # Render the middle as a TEXT transcript instead of replaying the raw
    # messages — the slice can open on tool messages whose paired
    # assistant call lives outside it, and strict OpenAI-compatible
    # servers 400 on orphaned tool results.
    transcript = Enum.map_join(middle, "\n", &render_line/1)
    req_messages = [Messages.user(transcript <> "\n\n" <> instruction)]

    request = %Request{
      messages: req_messages,
      system_prompt: nil,
      model: state.request_template && state.request_template.model,
      max_tokens: 512,
      temperature: 0.2,
      timeout_ms: 30_000
    }

    # Through the shared inference path: GPU-queue slot (a compaction call
    # must not oversubscribe a 1-slot local backend while a sibling worker
    # is mid-call), chat telemetry, and the summary call's usage/cost
    # folded onto the run's budget. `chat_params: false` — a fixed
    # micro-budget utility call must not be reshaped by conversational
    # per-turn hooks. `starvation: :tolerate` — a starved summary is just
    # an empty summary (`{:error, :empty_summary}` below); it must not
    # trigger the kernel's max_tokens escalation.
    result =
      ExAthena.Loop.Inference.call(state, request,
        purpose: :compaction_summary,
        starvation: :tolerate,
        chat_params: false
      )

    case result do
      {:ok, %{text: text}, folded_state} when is_binary(text) and text != "" ->
        {:ok, text, folded_state.budget}

      {:ok, _response, _state} ->
        {:error, :empty_summary}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp render_line(%{role: :tool, tool_results: [tr | _]}) when not is_nil(tr) do
    "[tool result] " <> String.slice(to_string(tr.content || ""), 0, 500)
  end

  defp render_line(%{role: role, content: content, tool_calls: calls}) do
    calls_part =
      case calls do
        list when is_list(list) and list != [] ->
          " [calls: " <> Enum.map_join(list, ", ", & &1.name) <> "]"

        _ ->
          ""
      end

    "[#{role}] " <> String.slice(to_string(content || ""), 0, 1_000) <> calls_part
  end

  defp split_messages(messages, pinned_count, live_count) do
    total = length(messages)

    cond do
      total <= pinned_count + live_count ->
        {messages, [], []}

      true ->
        {prefix, rest} = Enum.split(messages, pinned_count)
        split_at = max(0, length(rest) - live_count)
        # Snap the middle/suffix boundary so the live suffix never STARTS
        # with tool messages whose paired assistant call got summarized
        # away (orphaned tool_result → 400 on strict servers). Grow the
        # suffix backwards until it opens on a non-tool message.
        split_at = snap_to_pair_boundary(rest, split_at)
        {middle, suffix} = Enum.split(rest, split_at)
        {prefix, middle, suffix}
    end
  end

  defp snap_to_pair_boundary(_rest, 0), do: 0

  defp snap_to_pair_boundary(rest, split_at) do
    case Enum.at(rest, split_at) do
      %{role: :tool} -> snap_to_pair_boundary(rest, split_at - 1)
      _ -> split_at
    end
  end

  # Effective pinned prefix = configured prefix slots + however many
  # memory-context messages and pre-loaded skill activation messages got
  # prepended at run start. Memory and pre-loaded skills (PR1) live at
  # the top of the message list, so we extend the pin floor to keep
  # them safe across compactions.
  defp effective_pinned_prefix_count(%State{meta: meta} = state) do
    pinned_prefix_count(state) +
      Map.get(meta, :memory_count, 0) +
      Map.get(meta, :preloaded_skill_count, 0)
  end

  defp pinned_prefix_count(%State{} = state),
    do: Config.get(state, :pinned_prefix_count, @default_pinned_prefix_count)

  defp live_suffix_count(%State{} = state),
    do: Config.get(state, :live_suffix_count, @default_live_suffix_count)

  defp compact_at(%State{} = state), do: Config.get(state, :compact_at, @default_compact_at)

  # Deliberately app-env only (no per-run meta override existed before the
  # Config extraction, and none is introduced by it).
  defp summary_system_prompt do
    Config.app_env(
      :summary_system_prompt,
      "You are a compaction assistant. Your only job is to summarise a portion of a " <>
        "conversation between an engineer and an AI agent so the agent can continue " <>
        "without the full transcript."
    )
  end
end
