defmodule ExAthena.Web.FileController do
  @moduledoc """
  Serves a file from the session's working directory to the browser.

  Two actions, both in the router's `:browser` pipeline, so
  `ExAthena.Web.Auth` gates them exactly as it gates the chat itself. The app
  binds `0.0.0.0` under `mix athena.web --host`, so that is a real boundary.

  ## Confinement

  The root is not a parameter the caller chooses: it arrives as a
  `Phoenix.Token` this server signed (`ExAthena.Web.FileLinks`), and the
  resolved path must satisfy `ExAthena.Web.Files.resolve/2`, which canonicalizes
  every symlink component through `ExAthena.ToolContext.within_roots?/2` before
  comparing path segments. `..`, an absolute path elsewhere, and a symlink
  inside the root pointing out are all refused by that one function. This
  module adds no path check of its own — a second copy would drift.

  ## Why `preview` is sandboxed

  The HTML it renders was written by a model. Serving it on the app's own
  origin would hand model-authored script the user's session cookie, the
  chat's DOM and every LiveView event. So the response carries:

    * `content-security-policy: sandbox allow-scripts` — the document gets an
      **opaque origin**: no cookies, no `localStorage`, no access to the parent
      document, no form submission, no top-level navigation. `allow-scripts`
      is granted because a brief that draws its own diagrams is the point of
      the feature; it is only dangerous paired with `allow-same-origin`, which
      is never set here or on the iframe that frames it.
    * `x-content-type-options: nosniff` — the bytes are rendered as the type
      we declare, never as one the browser guesses.
    * `referrer-policy: no-referrer` — a mock that fetches an external asset
      must not leak the path it was served from.
    * `cache-control: no-store` — the file is regenerated by runs; a cached
      copy would show stale work.

  `x-frame-options: SAMEORIGIN` from `put_secure_browser_headers` is left as
  it is: the only page allowed to frame a preview is this app's own.
  """
  use Phoenix.Controller, formats: [:html]

  alias ExAthena.Web.FileLinks
  alias ExAthena.Web.Files

  @csp_sandbox "sandbox allow-scripts"

  @doc "Send the file at `path` as an attachment, whatever its type."
  def download(conn, params) do
    case confined_path(params) do
      {:ok, path} ->
        conn
        |> put_resp_content_type("application/octet-stream", nil)
        |> put_resp_header("content-disposition", content_disposition(Path.basename(path)))
        |> put_resp_header("x-content-type-options", "nosniff")
        |> put_resp_header("cache-control", "no-store")
        |> send_file(200, path)

      {:error, reason} ->
        refuse(conn, reason)
    end
  end

  @doc "Render an HTML file as a page, in an opaque origin. See the moduledoc."
  def preview(conn, params) do
    with {:ok, path} <- confined_path(params),
         true <- FileLinks.previewable?(path) do
      conn
      |> put_resp_content_type("text/html")
      |> put_resp_header("content-security-policy", @csp_sandbox)
      |> put_resp_header("x-content-type-options", "nosniff")
      |> put_resp_header("referrer-policy", "no-referrer")
      |> put_resp_header("cache-control", "no-store")
      |> send_file(200, path)
    else
      false -> refuse(conn, :not_previewable)
      {:error, reason} -> refuse(conn, reason)
    end
  end

  # ---------------------------------------------------------------------------
  # Internals
  # ---------------------------------------------------------------------------

  defp confined_path(params) do
    with {:ok, root} <- FileLinks.verify_root(params["root"]),
         path when is_binary(path) <- params["path"] do
      Files.regular_file(root, path)
    else
      nil -> {:error, :invalid}
      {:error, reason} -> {:error, reason}
      _other -> {:error, :invalid}
    end
  end

  # One refusal shape per class, and no detail about what exists where: a 404
  # that only ever appeared for real files would confirm their presence to a
  # caller who cannot read them.
  defp refuse(conn, reason) do
    {status, body} =
      case reason do
        :no_such_file -> {404, "Not found\n"}
        :not_a_file -> {404, "Not found\n"}
        :not_previewable -> {415, "This file is not previewable; download it instead.\n"}
        _outside_or_invalid -> {403, "Forbidden\n"}
      end

    conn
    |> put_resp_content_type("text/plain")
    |> put_resp_header("cache-control", "no-store")
    |> send_resp(status, body)
  end

  # RFC 6266: the quoted `filename` for every client, `filename*` so a
  # non-ASCII name survives. Quotes, backslashes and control characters are
  # replaced rather than escaped — a filename cannot be allowed to end the
  # quoted string and start writing header parameters of its own.
  defp content_disposition(name) do
    ascii = String.replace(name, ~r/[^\x20-\x7E]|["\\]/, "_")
    encoded = URI.encode(name, &URI.char_unreserved?/1)

    ~s(attachment; filename="#{ascii}"; filename*=UTF-8''#{encoded})
  end
end
